apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: test-app-ns
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
    {{- if .Values.vaultEnabled }}
      annotations:
        {{- range $key, $val := .Values.annotations }}
        {{ $key }}: {{ $val | quote }}
        {{- end }}
    {{- end }}
      labels:
        app: {{ .Values.appName }}
        app.kubernetes.io/name: {{ .Values.appName }}
        app.kubernetes.io/version: {{ .Values.container.tagVersion }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                - {{ .Values.appName }}
              - key: "app.kubernetes.io/version"
                operator: In
                values:
                - {{ .Values.container.tagVersion }}
            topologyKey: kubernetes.io/hostname
      containers:
        - image: 239534/test_app:{{ .Values.container.tagVersion }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          name: {{ .Values.appName }}
          readinessProbe:
            periodSeconds: {{ .Values.probes.readinessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.probes.readinessProbe.initialDelaySeconds }}
            httpGet:
              path: /test_uri
              port: 5000
          livenessProbe:
            httpGet:
              path: /test_uri
              port: 5000
            initialDelaySeconds: {{ .Values.probes.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.livenessProbe.periodSeconds }}
          ports:
            - containerPort: 5000
      serviceAccountName: {{ .Values.appName }}-sa