apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test-app-ns
  name: {{ .Values.appName }}-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "watch", "list"]